import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { removeTreeSafely } from './home-manager.js';
import { ensureDir } from './util.js';

const here = path.dirname(fileURLToPath(import.meta.url));

export const FIXTURE_SESSION_ID = 'session-00000000-0000-4000-8000-000000000001';
export const FIXTURE_SESSION_TITLE = 'Lab fixed session';

/** Committed fixture specs; `default` is the single-turn conversation. */
export const FIXTURE_VARIANTS = {
  default: 'fixed-session.json',
  empty: 'empty-session.json',
  long: 'long-session.json',
  rich: 'rich-session.json',
};

export function seederPluginDir() {
  return path.resolve(here, '..', 'fixtures', 'plugins', 'session-seeder');
}

export function webSessionDir() {
  return path.resolve(here, '..', 'fixtures', 'web-session');
}

export function fixtureVariantPath(variant = 'default') {
  const file = FIXTURE_VARIANTS[variant];
  if (!file) throw new Error(`unknown fixture variant: ${variant}`);
  return path.join(webSessionDir(), file);
}

export function readFixtureSpec(variant = 'default') {
  return JSON.parse(fs.readFileSync(fixtureVariantPath(variant), 'utf8'));
}

/**
 * Create a workspace with stable files for the conversation fixture.
 *
 * A persistent lab profile reuses its home between runs, so the default fixed
 * `fixture-workspace` accumulates sessions from earlier runs and the UI can
 * open a stale/empty one. Callers pass a per-run `name` to keep the seeded
 * session the only one under that workspace.
 */
export function createFixtureWorkspace(root, options = {}) {
  const name = String(options.name ?? 'fixture-workspace').replace(/[^A-Za-z0-9._-]/g, '-') || 'fixture-workspace';
  const workspace = ensureDir(path.join(root, name));
  fs.writeFileSync(
    path.join(workspace, 'README.md'),
    '# Lab fixture workspace\n\nThis workspace is generated by DSH Plugin Effect Lab.\n',
    'utf8',
  );
  fs.writeFileSync(
    path.join(workspace, 'notes.txt'),
    'Fixed workspace fixture. No real project or session is used.\n',
    'utf8',
  );
  return workspace;
}

export function fixtureEnv(options = {}) {
  const {
    enabled = true,
    sessionId = FIXTURE_SESSION_ID,
    cwd,
    variant = null,
  } = options;
  const file = enabled && variant ? fixtureVariantPath(variant) : null;
  return {
    DSH_LAB_FIXTURE_ENABLED: enabled ? '1' : '0',
    DSH_LAB_FIXTURE_SESSION_ID: sessionId,
    ...(cwd ? { DSH_LAB_FIXTURE_CWD: cwd } : {}),
    ...(file ? { DSH_LAB_FIXTURE_FILE: file } : {}),
  };
}

/**
 * Make a lab home deterministic for a fixture run.
 *
 * A persistent lab profile keeps its home between runs, and a fixture-less run
 * (for example the clone-creation / --force pass) leaves DSH's own
 * `default-workspace` plus an untitled session behind. On the next
 * fixture-enabled run DSH keeps that stale workspace active, only the default
 * workspace's session list is reconciled, and the freshly-seeded fixture
 * workspace is never rendered or selected — `shell-fixture-session` then fails
 * with `session=false` even though the fixture session exists over RPC.
 *
 * The lab home is isolated and lab-owned, so a fixture run can clear its
 * `sessions/` and `storages/` before the host starts; the fixture is reseeded
 * under the only workspace. `--no-fixture` runs never call this.
 */
export function resetLabWorkspaceState(homeDir) {
  const removed = [];
  for (const name of ['sessions', 'storages']) {
    const dir = path.join(homeDir, name);
    if (fs.existsSync(dir)) {
      removeTreeSafely(dir);
      removed.push(dir);
    }
  }
  return { removed };
}
