import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ensureDir } from './util.js';

const here = path.dirname(fileURLToPath(import.meta.url));

export const FIXTURE_SESSION_ID = 'session-00000000-0000-4000-8000-000000000001';
export const FIXTURE_SESSION_TITLE = 'Lab fixed session';

export function seederPluginDir() {
  return path.resolve(here, '..', 'fixtures', 'plugins', 'session-seeder');
}

/** Create a fixed workspace with stable files for the conversation fixture. */
export function createFixtureWorkspace(root) {
  const workspace = ensureDir(path.join(root, 'fixture-workspace'));
  fs.writeFileSync(
    path.join(workspace, 'README.md'),
    '# Lab fixture workspace\n\nThis workspace is generated by DSH Plugin Effect Lab.\n',
    'utf8',
  );
  fs.writeFileSync(
    path.join(workspace, 'notes.txt'),
    'Fixed workspace fixture. No real project or session is used.\n',
    'utf8',
  );
  return workspace;
}

export function fixtureEnv(options = {}) {
  const {
    enabled = true,
    sessionId = FIXTURE_SESSION_ID,
    cwd,
  } = options;
  return {
    DSH_LAB_FIXTURE_ENABLED: enabled ? '1' : '0',
    DSH_LAB_FIXTURE_SESSION_ID: sessionId,
    ...(cwd ? { DSH_LAB_FIXTURE_CWD: cwd } : {}),
  };
}
