import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { removeTreeSafely } from './home-manager.js';
import { ensureDir } from './util.js';

const here = path.dirname(fileURLToPath(import.meta.url));

export const FIXTURE_SESSION_ID = 'session-00000000-0000-4000-8000-000000000001';
export const FIXTURE_SESSION_TITLE = 'Lab fixed session';

/** Committed fixture specs; `default` is the single-turn conversation. */
export const FIXTURE_VARIANTS = {
  default: 'fixed-session.json',
  empty: 'empty-session.json',
  long: 'long-session.json',
  rich: 'rich-session.json',
};

export function seederPluginDir() {
  return path.resolve(here, '..', 'fixtures', 'plugins', 'session-seeder');
}

export function webSessionDir() {
  return path.resolve(here, '..', 'fixtures', 'web-session');
}

export function fixtureVariantPath(variant = 'default') {
  const file = FIXTURE_VARIANTS[variant];
  if (!file) throw new Error(`unknown fixture variant: ${variant}`);
  return path.join(webSessionDir(), file);
}

export function readFixtureSpec(variant = 'default') {
  return JSON.parse(fs.readFileSync(fixtureVariantPath(variant), 'utf8'));
}

/**
 * Create a workspace with stable files for the conversation fixture.
 *
 * A persistent lab profile reuses its home between runs, so the default fixed
 * `fixture-workspace` accumulates sessions from earlier runs and the UI can
 * open a stale/empty one. Callers pass a per-run `name` to keep the seeded
 * session the only one under that workspace.
 */
export function createFixtureWorkspace(root, options = {}) {
  const name = String(options.name ?? 'fixture-workspace').replace(/[^A-Za-z0-9._-]/g, '-') || 'fixture-workspace';
  const workspace = ensureDir(path.join(root, name));
  fs.writeFileSync(
    path.join(workspace, 'README.md'),
    '# Lab fixture workspace\n\nThis workspace is generated by DSH Plugin Effect Lab.\n',
    'utf8',
  );
  fs.writeFileSync(
    path.join(workspace, 'notes.txt'),
    'Fixed workspace fixture. No real project or session is used.\n',
    'utf8',
  );
  return workspace;
}

export function fixtureEnv(options = {}) {
  const {
    enabled = true,
    sessionId = FIXTURE_SESSION_ID,
    cwd,
    variant = null,
  } = options;
  const file = enabled && variant ? fixtureVariantPath(variant) : null;
  return {
    DSH_LAB_FIXTURE_ENABLED: enabled ? '1' : '0',
    DSH_LAB_FIXTURE_SESSION_ID: sessionId,
    ...(cwd ? { DSH_LAB_FIXTURE_CWD: cwd } : {}),
    ...(file ? { DSH_LAB_FIXTURE_FILE: file } : {}),
  };
}

/**
 * The session ids owned by the lab fixture. Only these are ever cleared from a
 * profile home; the user's own sessions are left alone.
 */
export function labFixtureSessionIds() {
  const ids = [];
  for (const file of Object.values(FIXTURE_VARIANTS)) {
    try {
      const spec = JSON.parse(fs.readFileSync(path.join(webSessionDir(), file), 'utf8'));
      if (spec.sessionId) ids.push(spec.sessionId);
    } catch {
      // A missing/broken spec is reported by the variant test instead.
    }
  }
  return [...new Set(ids)];
}

/**
 * Remove the lab fixture's own session files and their projection-cache
 * entries from an isolated home.
 *
 * A persistent profile keeps its home between runs, so an old fixture session
 * (and its cache entry) can survive. The seeder then sees `stat()` true and
 * skips writing, while the UI renders a stale/empty row. Clearing only the
 * lab-owned fixture ids makes each run seed the current variant fresh without
 * touching the user's sessions.
 */
export function clearLabFixtureState(homeDir) {
  const ids = new Set(labFixtureSessionIds());
  const removed = [];
  const sessionsRoot = path.join(homeDir, 'sessions');
  if (fs.existsSync(sessionsRoot)) {
    const walk = (dir) => {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          if (ids.has(entry.name)) {
            removeTreeSafely(full);
            removed.push(full);
          } else {
            walk(full);
          }
        }
      }
    };
    walk(sessionsRoot);
  }
  const cacheDir = path.join(homeDir, 'storages', 'session_projcache', 'sessions');
  if (fs.existsSync(cacheDir)) {
    for (const id of ids) {
      const file = path.join(cacheDir, `${id}.json`);
      if (fs.existsSync(file)) {
        removeTreeSafely(file);
        removed.push(file);
      }
    }
  }
  return { removed };
}
